max_blocking_threads = 128
message_framed_buffer_size = 2097152
port = 80
rsa_root_dir = "./rsa/"
target_buffer_size = 2097152
#port = 9999
agent_connection_read_timeout = 30
agent_stream_so_linger = 5
compress = true
so_backlog = 2048
target_stream_so_linger = 20
thread_number = 2048
thread_timeout = 10
#so_recv_buffer_size=8192
#so_send_buffer_size=262144
